---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role hive
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: check if downloaded and extracted
  stat: path={{ HADOOP_COMMON_USER_HOME }}/hive-{{ HIVE_VERSION }}-bin
  register: extracted_dir

- name: distribution downloaded
  get_url: >
    url={{ hive_dist.url }}
    sha256sum={{ hive_dist.sha256sum }}
    validate_certs=no
    dest=/tmp
  when: not extracted_dir.stat.exists

- name: distribution extracted
  shell: >
    chdir={{ HADOOP_COMMON_USER_HOME }}
    tar -xzf /tmp/{{ hive_dist.filename }} && chown -R {{ hadoop_common_user }}:{{ hadoop_common_group }} hive-{{ HIVE_VERSION }}-bin
  when: not extracted_dir.stat.exists

- name: versioned directory symlink created
  file: >
    src={{ HADOOP_COMMON_USER_HOME }}/hive-{{ HIVE_VERSION }}-bin
    dest={{ HIVE_HOME }}
    owner={{ hadoop_common_user }} group={{ hadoop_common_group }} state=link

- name: configuration installed
  template: >
    src={{ item }}.j2
    dest={{ HIVE_CONF }}/{{ item }}
    mode=0640 owner={{ hadoop_common_user }} group={{ hadoop_common_group }}
  with_items:
    - hive-env.sh

- name: env vars sourced in bashrc
  lineinfile: >
    dest={{ HADOOP_COMMON_USER_HOME }}/.bashrc state=present
    regexp="^source {{ HIVE_CONF }}/hive-env.sh" line="source {{ HIVE_CONF }}/hive-env.sh"
