---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role sqoop
# 

SQOOP_VERSION: 1.4.5
SQOOP_MYSQL_CONNECTOR_VERSION: 5.1.29
SQOOP_HOME: "{{ HADOOP_COMMON_USER_HOME }}/sqoop"
SQOOP_CONF: "{{ SQOOP_HOME }}/conf"
SQOOP_LIB: "{{ SQOOP_HOME }}/lib"

#
# vars are namespace with the module name.
#
sqoop_role_name: sqoop
sqoop_dist:
  filename: "sqoop-{{ SQOOP_VERSION }}.bin__hadoop-2.0.4-alpha.tar.gz"
  url: "http://www.carfab.com/apachesoftware/sqoop/1.4.5/sqoop-1.4.5.bin__hadoop-2.0.4-alpha.tar.gz"
  sha256sum: 2f36ba52ae64f2f674780984aa4ed53d43565098f208a4fcbd800af664b1def9
sqoop_mysql_connector_dist:
  filename: "mysql-connector-java-{{ SQOOP_MYSQL_CONNECTOR_VERSION }}.tar.gz"
  url: "http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ SQOOP_MYSQL_CONNECTOR_VERSION }}.tar.gz"
  sha256sum: 04ad83b655066b626daaabb9676a00f6b4bc43f0c234cbafafac1209dcf1be73

#
# OS packages
#

sqoop_debian_pkgs: []

sqoop_redhat_pkgs: []
