---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role hadoop_common
# 

#
# vars are namespace with the module name.
#

HADOOP_COMMON_VERSION: 2.3.0
HADOOP_COMMON_USER_HOME: /home/hadoop
HADOOP_COMMON_HOME: "{{ HADOOP_COMMON_USER_HOME }}/hadoop"
HADOOP_COMMON_DATA: /var/lib/hadoop/hdfs
HADOOP_COMMON_CONF_DIR: "{{ HADOOP_COMMON_HOME }}/etc/hadoop"

hadoop_user: hadoop
hadoop_group: hadoop
hadoop_common_role_name: hadoop_common
hadoop_dist:
  url: "https://archive.apache.org/dist/hadoop/core/hadoop-{{ HADOOP_COMMON_VERSION }}/hadoop-{{ HADOOP_COMMON_VERSION }}.tar.gz"
  sha256sum: 3fad58b525a47cf74458d0996564a2151c5a28baa1f92383e7932774deef5023
hadoop_common_java_home: /usr/lib/jvm/java-7-openjdk-amd64

#
# OS packages
#

hadoop_common_debian_pkgs:
  - openjdk-7-jdk

hadoop_common_redhat_pkgs: []
